<?php

namespace Modules\SmartForm\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CPMObjectiveSeedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // -
        // OPERATIONAL EXCELLENT
        // Productivity Loader
        // Productivity Coal
        // Productivity Hauler
        // ENGINEERING CAPABILITY
        // PHYSICAL AVAILABILITY (PA)
        // MEAN TIME BETWEEN FAILURE (MTBF)
        // MEAN TIME TO REPAIR (MTTR)
        // LIFE TIME
        // SHE INDEX
        // LOGISTIK & SM
        // ICGS
        // CVL
        // GENERAL SERVICE
        // DATA CENTER
        // INTERNAL AUDIT
        // LEGAL
        // BUSDEV  
        $tgl = now();

        $data_category = collect([
            ['nama' => '-', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'OPERATIONAL EXCELLENT', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'Productivity Loader', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'Productivity Coal', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'Productivity Hauler', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'ENGINEERING CAPABILITY', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'PHYSICAL AVAILABILITY (PA)', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'MEAN TIME BETWEEN FAILURE (MTBF)', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'MEAN TIME TO REPAIR (MTTR)', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'LIFE TIME', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'SHE INDEX', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'LOGISTIK & SM', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'ICGS', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'CVL', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'GENERAL SERVICE', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'DATA CENTER', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'INTERNAL AUDIT', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'LEGAL', 'created_by' => 'system', 'created_at' => $tgl],
            ['nama' => 'BUSDEV', 'created_by' => 'system', 'created_at' => $tgl],
        ]);
        $category_key = [];

        $data_obj = collect(array(
            array("nama" => "OB", "val1"=>"-"),
            array("nama" => "COAL", "val1"=>"-"),
            array("nama" => "SR", "val1"=>"-"),
            array("nama" => "COAL (in bcm)", "val1"=>"-"),
            array("nama" => "COAL Hauling", "val1"=>"-"),
            array("nama" => "Ton KM (Hauling)", "val1"=>"-"),
            array("nama" => "Jarak OB", "val1"=>"-"),
            array("nama" => "Jarak CO", "val1"=>"-"),
            array("nama" => "Jarak CO HAULING (KM)", "val1"=>"-"),
            array("nama" => "Ton KM", "val1"=>"-"),
            array("nama" => "Jarak CO HAULING", "val1"=>"-"),
            array("nama" => "PC2000 (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "PC2000 (Soft Material)", "val1"=>"Productivity Loader"),
            array("nama" => "PC2000 (Mud)", "val1"=>"Productivity Loader"),
            array("nama" => "PC1250 (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "PC1250 (Mud)", "val1"=>"Productivity Loader"),
            array("nama" => "XE900D (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "XE900D (Mud)", "val1"=>"Productivity Loader"),
            array("nama" => "ZX870/XE700D/850LC-9 (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "ZX870 (Mud)", "val1"=>"Productivity Loader"),
            array("nama" => "ZX470/PC400/E6500F", "val1"=>"Productivity Loader"),
            array("nama" => "PC2000", "val1"=>"Productivity Loader"),
            array("nama" => "SE980LCW", "val1"=>"Productivity Loader"),
            array("nama" => "XE930D", "val1"=>"Productivity Loader"),
            array("nama" => "XE900D", "val1"=>"Productivity Loader"),
            array("nama" => "ZX870 (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "XE700D (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "ZX350 (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "ZX350 (MUD)", "val1"=>"Productivity Loader"),
            array("nama" => "PC1250(OB)", "val1"=>"Productivity Loader"),
            array("nama" => "E6550F (OB) ", "val1"=>"Productivity Loader"),
            array("nama" => "X870H", "val1"=>"Productivity Loader"),
            array("nama" => "XE1250", "val1"=>"Productivity Loader"),
            array("nama" => "PC2000 (Sift Material)", "val1"=>"Productivity Loader"),
            array("nama" => "XE2000 (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "XE2000 (MUD)", "val1"=>"Productivity Loader"),
            array("nama" => "E6550F (OB)", "val1"=>"Productivity Loader"),
            array("nama" => "PC500 (CO)", "val1"=>"Productivity Coal"),
            array("nama" => "ZX470 (CO)", "val1"=>"Productivity Coal"),
            array("nama" => "ZX350 (CO)", "val1"=>"Productivity Coal"),
            array("nama" => "E6650F (CO)", "val1"=>"Productivity Coal"),
            array("nama" => "ZX200 (CO)", "val1"=>"Productivity Coal"),
            array("nama" => "XE900D", "val1"=>"Productivity Coal"),
            array("nama" => "ZX870/XE700D/850LC-9 (OB)", "val1"=>"Productivity Coal"),
            array("nama" => "E6350H", "val1"=>"Productivity Coal"),
            array("nama" => "PC1250", "val1"=>"Productivity Coal"),
            array("nama" => "ZX350", "val1"=>"Productivity Coal"),
            array("nama" => "E6550F", "val1"=>"Productivity Coal"),
            array("nama" => "HD785 (PC-2000)", "val1"=>"Productivity Hauler"),
            array("nama" => "HD785 (PC-1250) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "HD785 (PC-1250) (Mud)", "val1"=>"Productivity Hauler"),
            array("nama" => "HD465 (PC-1250) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "HD465 (PC-1250) (Mud)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (PC-1250) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (PC-1250) (Mud)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (XE900D) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (ZX870/XE700D/850LC) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (ZX870/XE700D/850LC) (Mud)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT96 (ZX870/XE700D/850LC) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT96 (ZX470/PC400/E6500F) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "RTH100 (PC-2000) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "RTH100 (PC-2000) (MUD)", "val1"=>"Productivity Hauler"),
            array("nama" => "RTH100 (PC-1250) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "RTH100 (PC-870) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "DT 38 Ton Hauling", "val1"=>"Productivity Hauler"),
            array("nama" => "DT 36 Ton Hauling", "val1"=>"Productivity Hauler"),
            array("nama" => "DT 30 Ton Hauling", "val1"=>"Productivity Hauler"),
            array("nama" => "DT 26 Ton Hauling", "val1"=>"Productivity Hauler"),
            array("nama" => "DONGFENG DF3310", "val1"=>"Productivity Hauler"),
            array("nama" => "ACTROS", "val1"=>"Productivity Hauler"),
            array("nama" => "EWH", "val1"=>"Productivity Hauler"),
            array("nama" => "UA", "val1"=>"Productivity Hauler"),
            array("nama" => "Road Condition Index (RCI) - OB", "val1"=>"Productivity Hauler"),
            array("nama" => "Road Condition Index (RCI) - CO", "val1"=>"Productivity Hauler"),
            array("nama" => "Dewatering Index (DWI)", "val1"=>"Productivity Hauler"),
            array("nama" => "Disposal Condition Index (DCI)", "val1"=>"Productivity Hauler"),
            array("nama" => "Front Condition Index (FCI) - OB", "val1"=>"Productivity Hauler"),
            array("nama" => "Front Condition Index (FCI) - CO", "val1"=>"Productivity Hauler"),
            array("nama" => "DONGFENG DFH3310A12", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (ZX870) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (ZX870) (MUD)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (XE700) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT 106 (ZX350) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT 106 (ZX350) (MUD)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (ZX470/PC400/E6500F) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106  (X6550F) (OB)        ", "val1"=>"Productivity Hauler"),
            array("nama" => "CMT106 (ZX870H) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "HD785 (PC-2000) (OB)", "val1"=>"Productivity Hauler"),
            array("nama" => "Join Survey vs Truck count", "val1"=>"ENGINEERING CAPABILITY"),
            array("nama" => "Mine Design Accuracy", "val1"=>"ENGINEERING CAPABILITY"),
            array("nama" => "Lead Time Berita Acara (BA)", "val1"=>"ENGINEERING CAPABILITY"),
            array("nama" => "Matching Factor", "val1"=>"ENGINEERING CAPABILITY"),
            array("nama" => "Fuel Ratio Mining", "val1"=>"ENGINEERING CAPABILITY"),
            array("nama" => "Fuel Ratio Hauling", "val1"=>"ENGINEERING CAPABILITY"),
            array("nama" => "(PA) - ALL CLUSTER", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - LOADING OB", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - LOADING CO", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - HAULING OB", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - MINING - HAULING CO", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - HAULING - HAULING CO", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - RIPDOZ", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - ROAD MAINTENANCE", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - DEWATERING", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - DRILL & BLAST", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - OTHER", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "(PA) - HAULING CO", "val1"=>"PHYSICAL AVAILABILITY (PA)"),
            array("nama" => "MTBF - ALL CLUSTER", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - LOADING OB", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - LOADING CO", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - HAULING OB", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - MINING - HAULING CO", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - HAULING - HAULING CO", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - RIPDOZ", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - ROAD MAINTENANCE", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - DEWATERING", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - DRILL & BLAST", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - OTHER", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTBF - HAULING CO", "val1"=>"MEAN TIME BETWEEN FAILURE (MTBF)"),
            array("nama" => "MTTR - ALL CLUSTER", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - LOADING OB", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - LOADING CO", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - HAULING OB", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - MINING - HAULING CO", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - HAULING - HAULING CO", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - RIPDOZ", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - ROAD MAINTENANCE", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - DEWATERING", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - DRILL & BLAST", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - OTHER", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "MTTR - HAULING CO", "val1"=>"MEAN TIME TO REPAIR (MTTR)"),
            array("nama" => "LIFE TIME TYRE 16.00 R25", "val1"=>"LIFE TIME"),
            array("nama" => "LIFE TIME TYRE 12.00 R24", "val1"=>"LIFE TIME"),
            array("nama" => "LIFE TIME TYRE 27.00 R49", "val1"=>"LIFE TIME"),
            array("nama" => "LIFE TIME TYRE 505/95 R29", "val1"=>"LIFE TIME"),
            array("nama" => "LIFE TIME COMPONEN ENGINE CMT96/CMT106", "val1"=>"LIFE TIME"),
            array("nama" => "REDO SERVICE", "val1"=>"LIFE TIME"),
            array("nama" => "BREAKDOWN SCHEDULE", "val1"=>"LIFE TIME"),
            array("nama" => "LIFE TIME TYRE", "val1"=>"LIFE TIME"),
            array("nama" => "LIFE TIME COMPONEN ENGINE", "val1"=>"LIFE TIME"),
            array("nama" => "BREAKDOWN SCHEDULE UNSCHEDULE", "val1"=>"LIFE TIME"),
            array("nama" => "BREAKDOWN UNSCHEDULE", "val1"=>"LIFE TIME"),
            array("nama" => "SHE Index", "val1"=>"SHE INDEX"),
            array("nama" => "SAFETY PERFORMANCE (TIFR)", "val1"=>"SHE INDEX"),
            array("nama" => "HEALTH PERFORMANCE (PAK FR)", "val1"=>"SHE INDEX"),
            array("nama" => "ENVIRO PERFORMANCE (EI)", "val1"=>"SHE INDEX"),
            array("nama" => "IBPR COMPLY", "val1"=>"SHE INDEX"),
            array("nama" => "FATALITY", "val1"=>"SHE INDEX"),
            array("nama" => "LTIFR (Lost Time Injury Frequency Rate)", "val1"=>"SHE INDEX"),
            array("nama" => "OHD (Occupational Health Diseases)/ PAK (Penyakit Akibat Kerja)", "val1"=>"SHE INDEX"),
            array("nama" => "SAP Achievement (Safety Accountability Program)", "val1"=>"SHE INDEX"),
            array("nama" => "FMP Achievement (Fatigue Management Program)", "val1"=>"SHE INDEX"),
            array("nama" => "OHIH Achievement (Occupational Health & Hygiene Industry)", "val1"=>"SHE INDEX"),
            array("nama" => "TSM Achievement (Traffic Safety Management)", "val1"=>"SHE INDEX"),
            array("nama" => "ERP Level (Emergency Response & Preparedness Level 2)", "val1"=>"SHE INDEX"),
            array("nama" => "EPP Achievement (Enviro Protection Program)", "val1"=>"SHE INDEX"),
            array("nama" => "FPMP Achievement  (Fire Protection Management Program)", "val1"=>"SHE INDEX"),
            array("nama" => "CAPA  Achievement (Closing ALL CAPA)", "val1"=>"SHE INDEX"),
            array("nama" => "MIFR (Minor Injury Frequency Rate)", "val1"=>"SHE INDEX"),
            array("nama" => "FIFR (Fire Incident Frequency Rate)", "val1"=>"SHE INDEX"),
            array("nama" => "PDFRate (Property Damage Frequency Rate)", "val1"=>"SHE INDEX"),
            array("nama" => "EIFR (Enviro Incident Frequency Rate)", "val1"=>"SHE INDEX"),
            array("nama" => "QSAP", "val1"=>"SHE INDEX"),
            array("nama" => "FIRE INCIDENT", "val1"=>"SHE INDEX"),
            array("nama" => "SERVICE RATIO (SR)", "val1"=>"LOGISTIK & SM"),
            array("nama" => "READINESS PARTS", "val1"=>"LOGISTIK & SM"),
            array("nama" => "INVENTORY TURN OVER (ITO)", "val1"=>"LOGISTIK & SM"),
            array("nama" => "PRODUKTIVITAS MP", "val1"=>"ICGS"),
            array("nama" => "ATTENDANCET RATIO (ATR)", "val1"=>"ICGS"),
            array("nama" => "EMPLOYEE TURN OVER RATIO (TOR)", "val1"=>"ICGS"),
            array("nama" => "RATIO MEKANIK : PENGAWAS", "val1"=>"ICGS"),
            array("nama" => "EMPLOYEE SATISFACTION INDEX", "val1"=>"ICGS"),
            array("nama" => "RATIO OPERATOR : PENGAWAS", "val1"=>"ICGS"),
            array("nama" => "LEADTIME PROJECT", "val1"=>"CVL"),
            array("nama" => "Achievement Maintanance Project", "val1"=>"CVL"),
            array("nama" => "AKURASI RAB", "val1"=>"CVL"),
            array("nama" => "Vendor Performance (%)", "val1"=>"GENERAL SERVICE"),
            array("nama" => "Arrival On Time Bus Sarana", "val1"=>"GENERAL SERVICE"),
            array("nama" => "Phisical Availability Bus", "val1"=>"GENERAL SERVICE"),
            array("nama" => "Phisical Availability Light Vehicle (LV)", "val1"=>"GENERAL SERVICE"),
            array("nama" => "Accuration Catering Order", "val1"=>"GENERAL SERVICE"),
            array("nama" => "Facility Performance (%)", "val1"=>"GENERAL SERVICE"),
            array("nama" => "Catering Delivery On Time", "val1"=>"GENERAL SERVICE"),
            array("nama" => "AKG", "val1"=>"GENERAL SERVICE"),
            array("nama" => "Asset GS Performance (%)", "val1"=>"GENERAL SERVICE"),
            array("nama" => "CSR Program", "val1"=>"GENERAL SERVICE"),
            array("nama" => "Kondusifitas Keamanan Project ", "val1"=>"GENERAL SERVICE"),
            array("nama" => "DATA DRIVEN", "val1"=>"DATA CENTER"),
            array("nama" => "CASH FLOW PROJECTION", "val1"=>"DATA CENTER"),
            array("nama" => "DATA GOVERNANCE ACHIEVEMENT", "val1"=>"DATA CENTER"),
            array("nama" => "BUDGET ACCURACY", "val1"=>"DATA CENTER"),
            array("nama" => "COST ACCURACY", "val1"=>"DATA CENTER"),
            array("nama" => "DATA QUALITY ACHIEVEMENT", "val1"=>"DATA CENTER"),
            array("nama" => "CENTRALIZED DATA ACHIEVEMENT", "val1"=>"DATA CENTER"),
            array("nama" => "INTEGRATED DATA ACHIEVEMENT", "val1"=>"DATA CENTER"),
            array("nama" => "ON TIME BUDGETING", "val1"=>"DATA CENTER"),
            array("nama" => "PARAMETER ACCURACY", "val1"=>"DATA CENTER"),
            array("nama" => "SPEND VARIANCE", "val1"=>"DATA CENTER"),
            array("nama" => "TIMELY REPORTING", "val1"=>"DATA CENTER"),
            array("nama" => "DATA VALIDATION", "val1"=>"DATA CENTER"),
            array("nama" => "REALTIME DATA INPUT", "val1"=>"DATA CENTER"),
            array("nama" => "GOOD ACCESSIBILITY", "val1"=>"DATA CENTER"),
            array("nama" => "DATA SECURITY ACHIEVEMENT", "val1"=>"DATA CENTER"),
            array("nama" => "INTERNAL AUDIT", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "INTERNAL AUDIT INDEX ", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "QUALITY ASSURANCE INTERNAL AUDIT ", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "COVERAGE SYSTEM", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "AUDIT SCORE", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "CLOSING TEMUAN AUDIT", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "INTERNAL AUDIT MANAGEMENT SYSTEM ", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "AKURASI SCHEDULE AUDIT ", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "LEAD TIME AUDIT REPORT", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "CONSULTATION & ASSISTANCE", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "CUSTOMER SATISFACTION INTERNAL AUDIT (INDEX)", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "AUDITEE SATISFACTION INTERNAL AUDIT (INDEX)", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "CASHFLOW RATIO", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "ROA", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "ROE", "val1"=>"INTERNAL AUDIT"),
            array("nama" => "LEGAL COMPLIANCE", "val1"=>"LEGAL"),
            array("nama" => "LEGAL CORPORATE ACHIEVEMENT", "val1"=>"LEGAL"),
            array("nama" => "DRAFTING/REVIEW PERJANJIAN", "val1"=>"LEGAL"),
            array("nama" => "TIME ACCURACY CONTRACT", "val1"=>"LEGAL"),
            array("nama" => "LEGAL KOMERSIL", "val1"=>"LEGAL"),
            array("nama" => "LITIGATION & NON LITIGATION SATISFACTION INDEX", "val1"=>"LEGAL"),
            array("nama" => "CASE MANAGEMENT REPORTS", "val1"=>"LEGAL"),
            array("nama" => "PROGRESS CASE REPORTS", "val1"=>"LEGAL"),
            array("nama" => "ANALISIS RESIKO", "val1"=>"LEGAL"),
            array("nama" => "PERMIT ACCURACY", "val1"=>"LEGAL"),
            array("nama" => "TIME PERMIT ACCURACY", "val1"=>"LEGAL"),
            array("nama" => "PARAMETER PERMIT ACCURACY", "val1"=>"LEGAL"),
            array("nama" => "BUSINESS DEVELOPMENT", "val1"=>"BUSDEV"),
            array("nama" => "BUSINESS INTELLIGENT", "val1"=>"BUSDEV"),
            array("nama" => "COMPETITOR ANALYST", "val1"=>"BUSDEV"),
            array("nama" => "VOLUME COMPETITOR", "val1"=>"BUSDEV"),
            array("nama" => "PROJECT AREA COMPETITOR", "val1"=>"BUSDEV"),
            array("nama" => "MARKET ANALYST", "val1"=>"BUSDEV"),
            array("nama" => "PROJECT MAP", "val1"=>"BUSDEV"),
            array("nama" => "NEW PROJECT DEVELOPMENT", "val1"=>"BUSDEV"),
            array("nama" => "PROSPECTING NEW PROJECT", "val1"=>"BUSDEV"),
            array("nama" => "ANALISA NEW PROJECT", "val1"=>"BUSDEV"),
            array("nama" => "FORECASTING NEW PROJECT", "val1"=>"BUSDEV"),
            array("nama" => "TENDER REQUIEREMENT", "val1"=>"BUSDEV"),
            array("nama" => "FEASIBILITY STUDY", "val1"=>"BUSDEV"),
            array("nama" => "OFFERING RATE", "val1"=>"BUSDEV"),
            array("nama" => "PROJECT MANAGEMENT", "val1"=>"BUSDEV"),
            array("nama" => "REGULER PROJECT REVIEW", "val1"=>"BUSDEV"),
            array("nama" => "MAINTAIN ISSUE PROJECT", "val1"=>"BUSDEV"),
            array("nama" => "ACH. PRODUKSI OB & COAL", "val1"=>"BUSDEV"),
            array("nama" => "CONTRACT MANAGEMENT", "val1"=>"BUSDEV"),
            array("nama" => "COMMERCIAL PROJECT REVIEW", "val1"=>"BUSDEV"),
            array("nama" => "CASH COST SENSITIVITY PROJECT", "val1"=>"BUSDEV"),
            array("nama" => "ACCOUNT RECEIVABLE", "val1"=>"BUSDEV"),
            array("nama" => "ON TIME PAYMENT", "val1"=>"BUSDEV"),
            array("nama" => "PROJECT SETTLEMENT", "val1"=>"BUSDEV"),
            array("nama" => "ACH. 4M + 1E", "val1"=>"BUSDEV"),
            array("nama" => "CONTRACT PREPARATION", "val1"=>"BUSDEV"),
            array("nama" => "SUSTAINIBILITY PROJECT", "val1"=>"BUSDEV"),
            array("nama" => "JOINT SIGN OPERATION", "val1"=>"BUSDEV"),
            array("nama" => "LIFE OF MINE PROJECT", "val1"=>"BUSDEV"),
            array("nama" => "COMPANY BRANDING", "val1"=>"BUSDEV"),
            array("nama" => "ACH. CONTENT DIGITAL", "val1"=>"BUSDEV"),
            array("nama" => "ACH. EVENT & SPONSORSHIP", "val1"=>"BUSDEV")
        ));

        foreach ($data_category as $value) {
            $idCategory = DB::table('cpm_m_obj_category')->insertGetId($value);
            if(!isset($category_key[$value['nama']])) {
                $category_key[$value['nama']] = $idCategory;
            }
        }

        foreach ($data_obj as $value1) {
            DB::table('cpm_m_obj')->insert([
                'nama' => $value1['nama'],
                'id_obj_category' => $category_key[$value1['val1']]
            ]);
        }
    }
}
